deployment:
  tasks:
    - export DEPLOYPATH=/home/bimanetc/public_html
    - /bin/cp -r * $DEPLOYPATH
    - /bin/find $DEPLOYPATH -type d -exec chmod 755 {} \;
    - /bin/find $DEPLOYPATH -type f -exec chmod 644 {} \;